# Generated by Django 5.2.15 on 2026-07-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Seeker', 'Seeker'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
