# Generated by Django 5.2.15 on 2026-07-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='jaafer ali', max_length=150),
            preserve_default=False,
        ),
    ]
